[package]
name         = "system2json"
version      = "0.1.0"
edition      = "2024"
rust-version = "1.85.1" # Minimum Supported Rust Version (MSRV)

[dependencies]
serde_json  = { version = ">=1.0.149, <2.0.0", optional = false, default-features = false, features = [ "std", "preserve_order" ] }
serde_json5 = { version = ">=0.2.1,   <1.0.0", optional = true,  default-features = false, features = [ ] }
serde_yaml  = { version = ">=0.9.34,  <1.0.0", optional = true,  default-features = false, features = [ ] }
toml        = { version = ">=1.0.6,   <2.0.0", optional = true,  default-features = false, features = [ "parse", "serde" ] }

[dev-dependencies]
serde       = { version = "=1.0.228", default-features = false, features = [ "derive" ] }

[features]
json5 = [ "dep:serde_json5" ]
toml  = [ "dep:toml" ]
yaml  = [ "dep:serde_yaml" ]
