[package]
name         = "desys"
edition      = "2024"

[dependencies]
serde_json5 = { version = ">=0.2.1,   <1.0.0", optional = false, default-features = false, features = [ ] }
serde_json  = { version = ">=1.0.149, <2.0.0", optional = false, default-features = false, features = [ "std", "preserve_order" ] }
serde       = { version = ">=1.0.228, <2.0.0", optional = false, default-features = false, features = [ ] }

[dev-dependencies]
serde       = { version = "=1.0.228", default-features = false, features = [ "derive" ] }
