asd = "file-json5://test-files/has-comments.jsonc"

[foo]
spam = "file://test-files/greeting.txt"
asd = "file-json5://test-files/has-comments.jsonc"

#
# Comment.
# 

[baz]
spam = "file://test-files/greeting.txt"
